name: Publish package

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Clean install dependencies
        run: |
          yarn install --immutable

      - name: Run linter
        run: |
          yarn lint

      - name: Run tests and report coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageCommand: yarn test:coverage

      - name: Publish package
        run: |
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
