name: Verify Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - name: Clean install dependencies
        run: |
          yarn install --immutable

      - name: Build project
        run: |
          yarn build

      - name: Run linter
        run: |
          yarn lint

      - name: Run tests and report coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageCommand: yarn test:coverage
